In [331]:
from sklearn import datasets
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import random
from sklearn.metrics import r2_score as r2

In [296]:
datasets=datasets.load_diabetes(as_frame=True)

In [297]:
data=datasets.data
target=pd.DataFrame(datasets.target)
targets=pd.DataFrame(target)

1.a

In [298]:
variance=pd.DataFrame(np.cov(data.T))
variance

0         1         2         3         4         5         6  \
0  0.002268  0.000394  0.000420  0.000761  0.000590  0.000497 -0.000170   
1  0.000394  0.002268  0.000200  0.000547  0.000080  0.000323 -0.000860   
2  0.000420  0.000200  0.002268  0.000897  0.000566  0.000592 -0.000832   
3  0.000761  0.000547  0.000897  0.002268  0.000550  0.000421 -0.000405   
4  0.000590  0.000080  0.000566  0.000550  0.002268  0.002033  0.000117   
5  0.000497  0.000323  0.000592  0.000421  0.002033  0.002268 -0.000445   
6 -0.000170 -0.000860 -0.000832 -0.000405  0.000117 -0.000445  0.002268   
7  0.000462  0.000753  0.000938  0.000584  0.001229  0.001496 -0.001675   
8  0.000614  0.000340  0.001012  0.000892  0.001169  0.000722 -0.000904   
9  0.000684  0.000472  0.000881  0.000885  0.000739  0.000659 -0.000621   

          7         8         9  
0  0.000462  0.000614  0.000684  
1  0.000753  0.000340  0.000472  
2  0.000938  0.001012  0.000881  
3  0.000584  0.000892  0.000885  
4  0.001229  0.001169  0.000739  
5  0.001496  0.000722  0.000659  
6 -0.001675 -0.000904 -0.000621  
7  0.002268  0.001401  0.000946  
8  0.001401  0.002268  0.001054  
9  0.000946  0.001054  0.002268

In [299]:
print(variance.shape)

(10, 10)


1.b

In [358]:
dataco=data.cov()
dataco

age       sex       bmi        bp        s1        s2        s3  \
age  0.002268  0.000394  0.000420  0.000761  0.000590  0.000497 -0.000170   
sex  0.000394  0.002268  0.000200  0.000547  0.000080  0.000323 -0.000860   
bmi  0.000420  0.000200  0.002268  0.000897  0.000566  0.000592 -0.000832   
bp   0.000761  0.000547  0.000897  0.002268  0.000550  0.000421 -0.000405   
s1   0.000590  0.000080  0.000566  0.000550  0.002268  0.002033  0.000117   
s2   0.000497  0.000323  0.000592  0.000421  0.002033  0.002268 -0.000445   
s3  -0.000170 -0.000860 -0.000832 -0.000405  0.000117 -0.000445  0.002268   
s4   0.000462  0.000753  0.000938  0.000584  0.001229  0.001496 -0.001675   
s5   0.000614  0.000340  0.001012  0.000892  0.001169  0.000722 -0.000904   
s6   0.000684  0.000472  0.000881  0.000885  0.000739  0.000659 -0.000621   

           s4        s5        s6  
age  0.000462  0.000614  0.000684  
sex  0.000753  0.000340  0.000472  
bmi  0.000938  0.001012  0.000881  
bp   0.000584  0.000892  0.000885  
s1   0.001229  0.001169  0.000739  
s2   0.001496  0.000722  0.000659  
s3  -0.001675 -0.000904 -0.000621  
s4   0.002268  0.001401  0.000946  
s5   0.001401  0.002268  0.001054  
s6   0.000946  0.001054  0.002268

In [300]:
#first find the covariance of age and bp
covariance=variance['age'][3] 
#find standard deviation from using covariance matrix and square rooting it
sdage=np.sqrt(dataco['age'][0])
sdbp=np.sqrt(dataco['bp'][3])
#plug into formula
correlation=covariance/(sdage*sdbp)
correlation

0.33542671054424283

In [301]:
np.corrcoef([data.age,data.bp]) #used to check

array([[1.        , 0.33542671],
       [0.33542671, 1.        ]])

1.c Since age and blood pressure are positively correlated, it means that as age increases, so does blood pressure. his means that we can expect older patients in this datasets to have higher blood pressure than young ones.


1.d

In [302]:
meanage=np.mean(data.age)
older=data[data['age']>meanage]
younger=data[data['age']<meanage]
olderbp=np.median(older.bp)
youngerbp=np.median(younger.bp)
print(olderbp)
print(youngerbp)
print(olderbp-youngerbp)
#the data has been standardized which is why the numbers seem weird

0.0115437429137471
-0.0228849640236156
0.0344287069373627


In [303]:
stage=np.std(data.bp)
(olderbp-youngerbp)/stage

0.7238221126281121

2a

In [330]:
regression=LinearRegression().fit(data,target)
Rsq=regression.score(data,target)
regcoef=regression.coef_
print(Rsq)
print(regcoef)
predictions = pd.DataFrame(reg.predict(data))
count=predictions.values-target.values
np.count_nonzero(count == 0)
#there are 0 instances

0.5177494254132934
[[ -10.01219782 -239.81908937  519.83978679  324.39042769 -792.18416163
   476.74583782  101.04457032  177.06417623  751.27932109   67.62538639]]


0

In [317]:
count

array([[  55.11706979],
       [  -6.92765239],
       [  35.88406035],
       [ -39.08203441],
       [  -6.54015759],
       [   9.34908972],
       [ -64.10582053],
       [  55.85378669],
       [  48.81033076],
       [ -96.41591107],
       [  -3.92146417],
       [  26.1016223 ],
       [ -63.93326699],
       [ -20.32394977],
       [ -14.92482054],
       [   6.17236996],
       [  45.75953205],
       [  38.84424343],
       [  50.99987605],
       [ -43.98297473],
       [  52.33094632],
       [  36.80377894],
       [  45.11286302],
       [   7.44934852],
       [ -18.51178944],
       [ -54.27812377],
       [ -39.87175925],
       [  94.09342974],
       [  -1.94502676],
       [ -98.21861448],
       [  29.71515746],
       [  10.47588393],
       [ -79.49744174],
       [  25.81897436],
       [  13.37194762],
       [ -14.33375871],
       [ -57.07539787],
       [-118.12313963],
       [ -11.15629314],
       [  46.93372685],
       [  53.48187659],
       [  19.157

2.b

In [355]:
#splits the indices and makes it random
indices=list(data.index.values)
shuffled = random.sample(indices, len(indices))
training=shuffled[:300]
test=shuffled[300:]
#located the rows of the indices
trainingdata=data.iloc[training]
testingdata=data.iloc[test]
trainingtarget=target.iloc[training]
testingtarget=target.iloc[test]
reg1=LinearRegression().fit(trainingdata,trainingtarget)
reg1score=reg1.score(trainingdata,trainingtarget)
predictions1 = reg1.predict(testingdata)
rsquaredtest = r2(testingtarget, predictions1)
print(reg1score)
print(rsquaredtest)

0.5294441547919385
0.4429658292263915


3

In [291]:
# Define Matrices and their mean shifts 
D=data
Y=target
D1=D-D.mean()
Y1=Y-Y.mean()
#create X transpose
Dtranspose=D.T
#Create X times X transpose
square =Dtranspose.dot(D)
#create the inverse of X times X transpose
invsquare=np.linalg.pinv(square)
c1=invsquare.dot(Dtranspose)
c2=c1.dot(Y1)
print(c2)
#C0 is simply the mean of Y which means that its value is 152.133
Y.mean()

[[ -10.01219782]
 [-239.81908937]
 [ 519.83978679]
 [ 324.39042769]
 [-792.18416163]
 [ 476.74583782]
 [ 101.04457032]
 [ 177.06417623]
 [ 751.27932109]
 [  67.62538639]]


target    152.133484
dtype: float64